#Application URL
url = https://opensource-demo.orangehrmlive.com/

#Browser Configuration
browser = chrome

#Credentials
username = admin
password = admin123

#Implicit Wait (in seconds)
implicitWait=10

#Explicit wait
explicitWait = 30

#Inorder to run in headless mode - set as true

